### ISSUE TITLE
51Degrees appears to be loading its database seven times, consuming ~2GB+

### ISSUE THREAD

**Issue by rslifka** [51Degreesmobi/51Degrees-Java#13]
Hello 51Degrees team!

We're investigating memory consumption beyond the heap in one of our applications and the top consumers (after the heap) are the following:

```
00007efb0a31d000  346072  203916       0 r--s- 51Degrees.dat
00007efb1f513000  346072  201196       0 r--s- 51Degrees.dat
00007efb34b0d000  346072  203980       0 r--s- 51Degrees.dat
00007efb49d03000  346072  200740       0 r--s- 51Degrees.dat
00007efb89c14000  346072  205312       0 r--s- 51Degrees.dat
00007efb9ee0a000  346072  206680       0 r--s- 51Degrees.dat
```

(the size of our data file is `354,374,801`)

Perhaps on a related note, we also see seven instances of `fiftyone.mobile.detection.readers.BinaryReader` present in memory though our HPROF viewer stalls when calculating the GC root so I can't provide more information.

Any idea what's happening here? Thank you!

**Comment by Steve51D** [comment]
Hi @rslifka,

Apologies for the delay in getting back to you. I'll pass this over to the team and get an answer as soon as we can.

**Comment by rslifka** [comment]
Thanks @Steve51D!

We're also not sure how these two repos are related to one another:

1. https://github.com/51Degrees/Java-Device-Detection (this one)
2. https://github.com/51Degrees/device-detection-java (another one?)

Should we be using (2)? Seems like (1) isn't actively maintained.

**Comment by Steve51D** [comment]
Hi @rslifka, 

Yes correct, we are no longer updating the codebase in this repo. However, we are continuing to support v3 customers who are using it by releasing new datafiles for Premium & Enterprise users.
 
https://github.com/51Degrees/device-detection-java is for version 4 of the API.
V4 was released earlier this year, we are happy to support customers who wish to upgrade from v3 to v4.

**Comment by Steve51D** [comment]
Closing this as v4 has resolved the issues raised.
