### ISSUE TITLE
Memory leak, 3.2.12.4

### ISSUE THREAD

**Issue by jonathanbl** [51Degreesmobi/51Degrees-Java#3]
Hi, 

We recently moved over to latest Java version API, 3.2.12.4 as well as the 51Degrees-PremiumV3_2.dat file from January 28th.  As soon as I moved to production with this setup, we saw a huge increase in memory usage and it quickly pointed out to a memory leak. Please see below for more details. 

Also, can you confirm if we can update our 51Degrees-PremiumV3_2.dat file without constantly updating the API?

Thank you,
Jonathan

**Comment by jonathanbl** [comment]
I was able to replicate this by running a local process, see screenshot below

<img width="1183" alt="screen shot 2017-02-11 at 11 43 59 am" src="https://cloud.githubusercontent.com/assets/1969907/22855522/8546ee9a-f04f-11e6-8019-1fb2a7aaace1.png">

**Comment by jonathanbl** [comment]
Link to the heap dump: https://storage.googleapis.com/everflow-sharing/heapdump-1486831384734.hprof.gz

**Comment by jonathanbl** [comment]
List of user agents I used for the tests

[user_agent.sql.zip](https://github.com/51Degrees/Java-Device-Detection/files/768788/user_agent.sql.zip)

**Comment by Joseph51D** [comment]
Hi @jonathanbl 

Thank you for raising this. I have contacted you privately with a solution.

If any one else has experienced these issues with release 3.2.12.4, please contact us via our website: [https://51degrees.com/contact-us](https://51degrees.com/contact-us), selecting Technical Question as the contact reason.

Regards,
Joseph

**Comment by plokhotnyuk** [comment]
It seems that main problem is an inefficient loop in a constructor of MostFrequentFilter instance during Provider.match call. It produces lot of Integer instances. Please see the following flame graph to see its impact:
![image](https://cloud.githubusercontent.com/assets/890289/23158043/e9992bb2-f81d-11e6-9840-36d69a4e36b6.png)

**Comment by jonathanbl** [comment]
@plokhotnyuk    what is the tool you are using to profile the code?

**Comment by plokhotnyuk** [comment]
I had used FlightRecorder profiler, than processed results by jfr-flame-graph and FlameGraph tools.
Here is a great introduction article about these stuff and other options: http://psy-lob-saw.blogspot.com/2017/02/flamegraphs-intro-fire-for-everyone.html

**Comment by jonathanbl** [comment]
That's great, thank you!

**Comment by plokhotnyuk** [comment]
Also don't miss Nitsan's talk about JVM profiling where he is digging much dipper, than in that introduction: https://www.youtube.com/watch?v=7PkkxDaFDj8

**Comment by Joseph51D** [comment]
We are currently have a solution for this issue in development. If you would like to be involved in testing, please email 'support @ 51degrees.com'.

**Comment by Joseph51D** [comment]
This issue has been resolved in the 3.2.13.9 release.

Thanks @jonathanbl for you help in testing this.
