### ISSUE TITLE
Change dependency scope for logback-{core, classic}

### ISSUE THREAD

**Issue by qerub** [51Degreesmobi/51Degrees-Java#4]
`device-detection-core` currently declares dependencies on `logback-{core, classic}` with `runtime` scope.

This makes the library unsuitable for use in applications that don't already use Logback, unless the workaround of excluding those transitive dependencies is used.

The [SLF4J manual](https://www.slf4j.org/manual.html) clearly states:

> **Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api.** When a library declares a transitive dependency on a specific binding, that binding is imposed on the end-user negating the purpose of SLF4J. Note that declaring a non-transitive dependency on a binding, for example for testing, does not affect the end-user.

Please change to `test` scope.

**Comment by Joseph51D** [comment]
Hi @qerub 

Thanks for bringing this to our attention. We will address this in our next release.

Regards,
Joe

**Comment by Joseph51D** [comment]
Hi @qerub 

Thanks for investigating, unfortunately this missed the cutoff for our April release. We will schedule it in for our net release.

Regards,
Joseph
