### ISSUE TITLE
Add option(s) to ignore locale/application/sdk specific parts of user agent

### ISSUE THREAD

**Issue by plokhotnyuk** [51Degreesmobi/51Degrees-Java#5]
User agent string from mobile devices contains locale, application (FB, Pinterest, Twitter, etc.) or SDK (Google Mobile Ads, etc.) specific parts:
```
Mozilla/5.0 (Linux; U; Android 4.2.2; en-gb; GT-P3110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 (Mobile; afma-sdk-a-v10298440.9683000.2) 
Mozilla/5.0 (Linux; Android 6.0.1; SM-G920F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/119.0.0.23.70;]
Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 [FBAN/FBIOS;FBAV/62.0.0.43.141;FBBV/36454510;FBRV/0;FBDV/iPad4,4;FBMD/iPad;FBSN/iPhone OS;FBSV/10.0.2;FBSS/2;FBCR/;FBID/tablet;FBLC/en_US;FBOP/5]
```
It greatly increases time of resolving (due case misses & longer matching time) for cases if that info is not required.

Best solution would be supplying of list of required properties during of DB loading that allow both: storing only required data for output and turning on best normalization strategy for user agent input.

**Comment by lily51degrees** [comment]
Hi Andriy

Thanks for the feedback, it is something we have in the PHP API, but has not yet been included in Java. I have sent this off to our development team and shall add it to list to be considered for development. I shall update this issue once we have had discussions.

Thanks again.

Michael

**Comment by Joseph51D** [comment]
Hi Andriy

51Degrees device detection does not evaluate User-Agents in this way. In short, the algorithm matches only the important sub strings of a User-Agent to a Profile Id in the data set, this then links to the Property:Value pairs referenced by that Profile Id.

On initialisation of the data set, you can specify which properties you would like to load and return values for. This, in a sense, achieves what you have suggested.

51Degrees device detection provides accurate detection of devices, not just the properties of a device that can be discerned from a User-Agent. Also, an important aspect of the algorithm is that character positions are considered, this provides added benefits such as fake User-Agent detection and discarding unimportant information.

Here’s is a link to the 51Degrees Pattern Data Model if you would like to know more:
[https://51degrees.com/support/documentation/device-detection-data-model](https://51degrees.com/support/documentation/device-detection-data-model)

And here is a link to how Pattern Device Detection works:
[https://51degrees.com/support/documentation/device-detection-data-model](https://51degrees.com/support/documentation/pattern)

Regards,

Joseph

**Comment by Joseph51D** [comment]
Hi Andiry,

I hope this answer was satisfactory. If not, please let us know. 

If you would like to get in touch, send us a message through the contact page on our website here: [https://51degrees.com/contact-us](https://51degrees.com/contact-us)

Regards,
Joseph

**Comment by plokhotnyuk** [comment]
Hi Joseph and Michael,

1) For initialization of dataset we use following call `MemoryFactory.create(file, false)`. We have tried turning on init option and StreamFactory, but matching performance is much worse for them. If you have option to filter out not required properties on loading of dataset, please let us know.

2) Current implementation of match result caching uses an original user agent string value: https://github.com/51Degrees/Java-Device-Detection/blob/fb541cbb423d823687446574b1b3e3261f83f18f/device-detection-core/src/main/java/fiftyone/mobile/detection/Provider.java#L518
It is lead to storing of dozen keys for the same result in case when the user agent contains locale or application/sdk specific part, that in case of limited size of the LRU cache lead to decreasing of cache efficiency in dozen times. It would be better to normalize keys before stroring to cache by stripping those noise parts of user agent values.
Let us say to got 99% of cache hits we should use cache sized for 1M entries, while most of them have duplicated values due key difference in locale, app or sdk part.

**Comment by Joseph51D** [comment]
The `StreamFactory` is slow compared to the `MemoryFactory` as the data set is not loaded into memory so it is going to be bottle-necked by the disk IO. There are cache options which you can apply to configure this for your environment

Below uses one of our templates which gets the best file stream performance for multiple threads in a low memory environment:
```
Dataset dataset = DatasetBuilder
    .file()
    .configureCaches(DatasetBuilder.CacheTemplate.MultiThreadLowMemory.getCacheConfiguration())
    .build(_dataFile);
```
Or configure each cache manually by using the `configureCache` method:
```
.configureCache(DatasetBuilder.CacheType.ProfilesCache, new CacheOptions(100, LruCache.builder()))
```
(See [cache field summary](https://51degrees.com/Portals/0/Documentation/Java/Docs/3.2.14.2/fiftyone/mobile/detection/DatasetBuilder.html#field_summary))


The behaviour of the LRU cache you describe is important for us as our detection capabilities are quite comprehensive. These parts of the User-Agents (application, SDK) allow us to populate the following values as described in the property dictionary on our site: [BrowserName](https://51degrees.com/resources/property-dictionary#BrowserName) and [IsWebApp](https://51degrees.com/resources/property-dictionary#IsWebApp) for example.

For situations where a different caching method is needed, the API has the ability to implement your own cache, take a look at this example which implements the [Google Guava cache](https://github.com/51Degrees/Java-Device-Detection/blob/master/device-detection-examples/src/main/java/fiftyone/device/example/illustration/CachingConfiguration.java
).
Using this as a base, you could implement the logic which strips out the noise parts of the User-Agent in the `put` and `get` methods, thereby removing the duplication you mentioned.

Hope this helps.

Also, can I ask what your business requirements are as we may be able to offer alternative solutions. If you are looking for raw performance then it might be worth taking a look at our Trie implementation instead which involves using the C API and using SWIG to translate to Java. This does use a lot of memory, but it is significantly faster. If you are interested then let me know.

Kind regards,
Joseph

**Comment by Joseph51D** [comment]
Hi @plokhotnyuk 

Let me know if my previous post was helpful or if you have any further questions so I can close this issue.

Regards,
Joseph
