### ISSUE TITLE
Support of audio streaming http clients

### ISSUE THREAD

**Issue by plokhotnyuk** [51Degreesmobi/51Degrees-Java#6]
Have you a plan to add support of them?
Current version of Enterprise DB v3.2.0.0 (Thu Apr 20 00:00:00 UTC 2017) cannot resolve properly most of user-agents from audio streaming players like bellow. All of them are resolved as desktop type devices while contains smartphone/tablet specific parts:
```
AlexaMediaPlayer/1.0.1905.13_1442710 (Linux;Android 5.1.1) ExoPlayerLib/1.5.9
CADENADIAL/3.0.0 iOS/10.2.1 iPhone/7,2 Union Radio/CADENADIAL
Cadena SER GT-P5100 STW Android (v1.08.25)
CadenaSER iPod touch STW (v3.0.4998)
CustomPlayer1/14 iOS/10.3.1 iPhone/8,2 Union Radio/CADENADIAL TdSdk/iOS-2.2.10
CustomPlayer1/2.0.2 Android/6.0.1 samsung-SM-J510FN UnionRadio/CADENASER TdSdk/android-2.4.4
GlobeNewspaper-RadioBDC iPod touch STW (v1.0.5373)
KBXXFM/Dalvik/2.1.0 (Linux; U; Android 6.0.1; LGLS775 Build/MMB29M)
KPIG 107.5 FM SAMSUNG-SGH-I577 STW (v2.08.08)
IjkExoMediaPlayer/4.1 (Linux;Android 6.0.1) ExoPlayerLib/1.5.11
PlayerService/v4.78361 (Linux;Android 5.0.2) ExoPlayerLib/1.5.8
rad.io 1.16 rv:585 (iPod touch 4G; iPhone OS 6.1.6; ja_JP)
Radiocom/v4.2.1/Android/4.4.2/ALCATEL A564C
SoundCloud/5.3.0 build 5092; iPad/iOS/10.3.1
SoundCloud-Android/2016.11.15-release (Android 4.2.2; TCT ALCATEL ONETOUCH P310A)
TJMSFM/Dalvik/2.1.0 (Linux; U; Android 7.0; SAMSUNG-SM-G935A Build/NRD90M)
TuneIn Radio/17.7 (Android 23; SHIELD Tablet; Java)
WFUNFM/Dalvik/2.1.0 (Linux; U; Android 6.0.1; HTCD160LVWPP Build/MMB29M)
```

**Comment by Joseph51D** [comment]
Hi @plokhotnyuk 

Apologies for the delay in response.

We’ve not had usage in any volume from cloud music services and therefore have not prioritised these finger prints. For now we've imported these User-Agents into our database so they should now evaluate correctly.

If you have any more User-Agents for which you are not seeing the expected results, you can send them to support@51degrees.com and we'll add them in for you.

We do offer a service called Usage Sharing where any User-Agent you see will be sent to us via a call to a cloud service. This allows us to collect these User-Agents and create Profiles for them.

Please see this guide on our site on how to enable Usage Sharing: [https://51degrees.com/Developers/Documentation/APIs/Java-V32/Web-Apps/Configuration/Usage-Sharing](https://51degrees.com/Developers/Documentation/APIs/Java-V32/Web-Apps/Configuration/Usage-Sharing)

Regards,
Joseph

**Comment by Joseph51D** [comment]
Hi @plokhotnyuk 

I hope this answer was satisfactory, or if you have any further questions please let me know.

Regards,
Joe
