### ISSUE TITLE
Is it possible to serialize 51degrees Provider?

### ISSUE THREAD

**Issue by MuhammadShaker** [51Degreesmobi/51Degrees-Java#9]
I have a spark job which uses 51degrees provider to parse user agents, it runs in cluster mode so I need to pass the provider to all cluster nodes thus it must be serializable.

How to fix this problem?
Thanks in advance.

**Comment by Joseph51D** [comment]
Hi @MuhammadShaker 

I'm afraid this isn't possible with the 51Degrees Java-Device-Detection API at the moment.

What you can do is serialize the data file in an object and pass that to all cluster nodes, then when the object is deserialized you can then create the provider on the nodes.

The better option however would be to make the data file available to all nodes on a shared file system e.g. HDFS and then set up the `Dataset` and `Provider` on the nodes.

Regards,
Joe

**Comment by MuhammadShaker** [comment]
Hi @Joseph51D, 

thanks for your suggestion, I solved my problem by using rrd.mapPartitions function, so I initialized the Provider for each partition in each node.

Best Regards.

**Comment by Joseph51D** [comment]
No problem, I'm glad you have found a solution.

Regards,
Joe
